import React, { useState, useEffect } from 'react';
import { Shield, FileText, CheckCircle, Info, Lock } from 'lucide-react';
import './PolicyPages.css';

export default function PolicyPages({ type }) {
  const [activeSection, setActiveSection] = useState('');

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [type]);

  const handleScrollTo = (id) => {
    setActiveSection(id);
    const element = document.getElementById(id);
    if (element) {
      const offset = 100; // Account for fixed header
      const bodyRect = document.body.getBoundingClientRect().top;
      const elementRect = element.getBoundingClientRect().top;
      const elementPosition = elementRect - bodyRect;
      const offsetPosition = elementPosition - offset;

      window.scrollTo({
        top: offsetPosition,
        behavior: 'smooth'
      });
    }
  };

  // Content Data
  const getPolicyContent = () => {
    switch (type) {
      case 'terms':
        return {
          title: 'Terms & Conditions',
          subtitle: 'Legal framework and user rules concluding your digital agreement with GHL India.',
          lastUpdated: 'December 19, 2025',
          sections: [
            {
              id: 'introduction',
              title: '1. Introduction & Concluding',
              icon: <FileText size={18} />,
              content: (
                <>
                  <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules made there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                  <p>This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement for access or usage of our website <a href="https://www.ghlindia.com" target="_blank" rel="noopener noreferrer">www.ghlindia.com</a> (the "Website").</p>
                  <p>The Platform refers to an internet based portal owned and operated by GHL India ("GHL"), having its registered office located at No.60/36, 5th Cross Street, Defence Colony, Nandambakkam, Chennai - 600032. (hereinafter, referred to as "we", "us", "our" and "GHL INDIA").</p>
                  <p>For the purpose of these User Terms, "you", "your" or "User" refers to any natural or legal person who accesses the Website, its contents and uses the services offered by GHL India on or through the Website. If you do not agree to these User Terms, you agree that your sole and exclusive remedy is to discontinue using the Website.</p>
                </>
              )
            },
            {
              id: 'registration',
              title: '2. Registration & Account',
              icon: <CheckCircle size={18} />,
              content: (
                <>
                  <p>To be eligible to register an account with us, you must be of such age that you can enter into legally binding agreements as per Applicable Laws where You reside in. If you use the Website or the Services on behalf of another individual or entity, you must be authorized by such individual or entity.</p>
                  <p>The Website and the offerings therein are intended only for registered Users who have completed the registration process and completed the KYC (Know-Your-Customer) requirements. Upon 'Acceptance' (which means your affirmative action in clicking on "Accept" button or any act which reflects your use of the Website), these User Terms will be effective and binding upon you.</p>
                  <p>You will be responsible for all activities that occur under your User ID or account. GHL India will not be liable to any person for any loss or damage which may arise as a result of any failure by the User to protect their User ID and/or the OTP.</p>
                </>
              )
            },
            {
              id: 'user-rights',
              title: '3. User Rights & Use Restrictions',
              icon: <Info size={18} />,
              content: (
                <>
                  <p>You confirm and acknowledge that by registering on the Website, you authorize and consent to GHL India sending promotional and marketing content to you through emails, phone calls, short message service or other electronic and non-electronic modes of communication.</p>
                  <p>The individual user will not use the Website in any way that is fraudulent or unlawful. Restrictions include:</p>
                  <ul>
                    <li>You shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Platform.</li>
                    <li>You shall not access the Platform in order to build a similar or competitive service.</li>
                    <li>You shall not copy, reproduce, distribute, republish, download, post, or transmit in any form or by any means, any part of the Platforms, for any commercial purpose.</li>
                    <li>You shall not upload viruses or malicious software, or attempt to systematically collect data from the site.</li>
                  </ul>
                </>
              )
            },
            {
              id: 'ownership',
              title: '4. Ownership of Materials',
              icon: <Shield size={18} />,
              content: (
                <>
                  <p>All platform content, compilation, logos, brand names, copyrights, trademarks, and trade dress on the Website are owned, controlled, or licensed by GHL India. Nothing on the Website will be interpreted as granting any license or right to use any trademark, logo, or service mark without prior written permission.</p>
                  <p>Individual users are entitled to view the Information on the Website and to copy and print such information for personal use only. Users are not permitted to sell or distribute or deal with the Information or any deviations of such information.</p>
                </>
              )
            },
            {
              id: 'no-offers',
              title: '5. No Offers or Reliance',
              icon: <Lock size={18} />,
              content: (
                <>
                  <p>The Website has been prepared solely for purposes of information. The information available on the Website is for convenience of presentation and under no circumstances should it be considered as an offer to sell or the invitation or solicitation of an offer to buy any asset listed on the Website.</p>
                  <p>GHL India does not give or offer any business advice, investment advice, tax or legal advice to anyone using this Website. Users should conduct their own due diligence and consult with their advisors. Assets displayed on the Website are not bank deposits, are not insured, and are not guaranteed by GHL India, and may lose value.</p>
                </>
              )
            },
            {
              id: 'liability',
              title: '6. Warranties & Limitation of Liability',
              icon: <FileText size={18} />,
              content: (
                <>
                  <p>The website and related services are provided on an "as is", "as available" and "with all faults" basis. GHL India and its associates specifically disclaim all warranties, whether expressed or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement.</p>
                  <p>Under no circumstances will GHL India or its associates be liable to you or anyone else for any direct, consequential, incidental, special, exemplary, punitive, or other indirect damages, including lost profits, trading losses, system failure, or hacker actions, resulting from the use or loss of use of the website.</p>
                </>
              )
            },
            {
              id: 'arbitration',
              title: '7. Arbitration & Governing Law',
              icon: <Shield size={18} />,
              content: (
                <>
                  <p>These User Terms will be governed and construed in accordance with the laws of India. If any dispute arises between you and GHL India, the dispute will be referred to a sole Arbitrator appointed by GHL India. The place of arbitration will be Chennai, Tamilnadu, and governed by the Arbitration & Conciliation Act, 1996.</p>
                  <p>Subject to arbitration, all disputes will be subject to the exclusive jurisdiction of courts at Chennai, Tamilnadu, India. Notices to GHL India should be sent to <a href="mailto:support@ghlindia.com">support@ghlindia.com</a>.</p>
                </>
              )
            }
          ]
        };

      case 'privacy':
        return {
          title: 'Privacy Policy',
          subtitle: 'GHL India Asset V PVT LTD is committed to protecting and respecting the privacy of every person.',
          lastUpdated: 'November 04, 2025',
          sections: [
            {
              id: 'intro',
              title: '1. Introduction & Consent',
              icon: <FileText size={18} />,
              content: (
                <>
                  <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules made there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                  <p>Thank you for visiting <a href="https://www.ghlindia.com" target="_blank" rel="noopener noreferrer">www.ghlindia.com</a> (the "Website"). GHL India Asset V PVT LTD is registered as GHL India Asset V PVT LTD having its registered office address at 2D, Queens Court, No.6, Montieth Road, Egmore, Chennai, Tamil Nadu-600 008, ("GHL India Asset V PVT LTD", "we", "us" or "our"). We are committed to protecting and respecting the privacy of every person who shares information with it or whose information it receives.</p>
                  <p>This Privacy Policy ("Privacy Policy") applies to the collection, receipt, storage, usage, processing, disclosure, transfer and protection ("Utilization") of your Personal Information (defined below) when the user of the Website ("User" or "you") uses our website or avails any services offered by GHL India Asset V PVT LTD through the Website.</p>
                  <p>By using the services or by otherwise giving us your information, you will be deemed to have read, understood and agreed to the practices and policies outlined in this privacy policy and agree to be bound by the privacy policy. You hereby consent to our collection, use and sharing, disclosure of your information as described in this privacy policy. We reserve the right to change, modify, add or delete portions of the terms of this privacy policy, at our sole discretion, at any time. If you do not agree with this privacy policy at any time, do not use any of the services or give us any of your information.</p>
                </>
              )
            },
            {
              id: 'consent-details',
              title: '2. Consent Guidelines',
              icon: <CheckCircle size={18} />,
              content: (
                <>
                  <p>You acknowledge that this Privacy Policy is a part of the User Terms of the Website and the other services, by accessing the Website or by otherwise providing Us with your Personal Information or by making use of the services provided by the Website, You unconditionally signify Your (i) assent to the Privacy Policy, and (ii) consent to the Utilisation of your Personal Information in accordance with the provisions of this Privacy Policy.</p>
                  <p>You acknowledge that you are over 18 years of age and are providing your Personal Information out of your free will.</p>
                  <p>You have the option not to provide us the Personal Information sought to be collected. You will also have an option to withdraw your consent at any point, provided such withdrawal of the consent is intimated to us in writing at <a href="mailto:support@ghlindia.com">support@ghlindia.com</a>. If you do not provide us your Personal Information or if you withdraw the consent, please note that your withdrawal of consent may result in GHL India Asset V PVT LTD being unable to provide you with its services or to terminate any existing relationship we may have with you.</p>
                  <p>Although the Website and services are not intended for use by minors, GHL India Asset V PVT LTD respects the privacy of minors who may inadvertently use the Website. We do not knowingly collect any Personal Information from children. Please contact us at <a href="mailto:support@ghlindia.com">support@ghlindia.com</a> if you are aware that we may have inadvertently collected details from a minor.</p>
                </>
              )
            },
            {
              id: 'collection',
              title: '3. Personal Information Collected',
              icon: <Info size={18} />,
              content: (
                <>
                  <p>We collect the following category of details (collectively referred to as "Personal Information"):</p>
                  <ul>
                    <li>Name of the User</li>
                    <li>Birth date/age and Gender</li>
                    <li>Address (including country and pin/postal code)</li>
                    <li>Financial and KYC information (such as passport, driving licence, proof of possession of Aadhaar number, Voter's Identity Card, or letter issued by the National Population Register containing details of name and address)</li>
                    <li>Phone number/mobile number and Email address</li>
                    <li>Records of interaction with GHL India Asset V PVT LTD’s representatives</li>
                    <li>Your usage details such as time, frequency, duration and pattern of use, features used and storage</li>
                    <li>Internet protocol (IP) address, browser type, browser language, referring URL, files accessed, operating system and other visitor details collected in Our log files ("Log Data")</li>
                  </ul>
                </>
              )
            },
            {
              id: 'non-personal',
              title: '4. Non-Personal Information',
              icon: <Shield size={18} />,
              content: (
                <>
                  <p>Company may also collect information other than Personal Information from user(s)/subscriber(s) through the Website/App when the user/subscriber visits and/or uses the Website/App. Such information may be stored in server logs. This Non-Personal Information would not assist Company to identify you personally.</p>
                  <p>We will automatically receive and collect certain anonymous information in standard usage logs through our Web server, including computer-identification information obtained from "cookies" sent to your browser, IP address, domain server, and browser/operating system type.</p>
                  <p>You can terminate your account at any time. However, your information may remain stored in archive on our servers even after the deletion or the termination of your account.</p>
                </>
              )
            },
            {
              id: 'mode-collection',
              title: '5. Mode of Collection of Information',
              icon: <FileText size={18} />,
              content: (
                <>
                  <p>We collect and store your Information provided by you from time to time. Our primary goal is to provide you a safe, efficient, smooth and customized experience.</p>
                  <p>We use data collection devices such as "cookies" on certain pages of the Website/App to help analyse our web page flow, measure promotional effectiveness, and promote trust and safety. Most cookies are "session cookies" automatically deleted at the end of a session. You are always free to decline our cookies if your browser permits.</p>
                  <p>If you transact with us, we may collect some additional information, such as a billing address, payment details, and tracking information from cheques or money orders.</p>
                  <p>If you choose to post messages or leave feedback on our message boards, chat rooms, or other areas, we will collect that information to resolve disputes and troubleshoot problems as permitted by law.</p>
                </>
              )
            },
            {
              id: 'usage',
              title: '6. Use of Personal Information',
              icon: <CheckCircle size={18} />,
              content: (
                <>
                  <p>Your Personal Information may be utilized for purposes including:</p>
                  <ul>
                    <li>To provide effective services and resolve customer support issues.</li>
                    <li>To operate and improve the Website.</li>
                    <li>To perform research and analysis to provide all users improved quality of care.</li>
                    <li>To contact you via phone, SMS or email for appointments, payment reminders, and announcements.</li>
                    <li>To send promotional and marketing emails from us or our channel partners.</li>
                    <li>For purposes of KYC verification and to build your profile/user account.</li>
                    <li>To prevent illegal activities, suspected fraud, or violations of our Terms of Use.</li>
                  </ul>
                </>
              )
            },
            {
              id: 'sharing',
              title: '7. Sharing & Transfer of Information',
              icon: <Shield size={18} />,
              content: (
                <>
                  <p>We may disclose Personal Information to our representatives and other third parties to comply with applicable laws. We provide details to our business partners, representatives, and third-party processors to administer services. You authorize us to exchange, transfer, or share your Personal Information across borders with affiliates, agents, banks, and financial institutions.</p>
                  <p>User’s financial information is transacted upon secure sites of approved payment gateways which are digitally under encryption. However, the User is advised to exercise discretion while saving payment details.</p>
                  <p>We are not responsible for security breaches or actions of third-parties beyond our reasonable control, including hacking, computer crashes, or breach of encryption.</p>
                </>
              )
            },
            {
              id: 'cookies-use',
              title: '8. Use of Cookies',
              icon: <Info size={18} />,
              content: (
                <>
                  <p>We, our third-party service providers and our partners may send "cookies" to your computer to enhance your online experience. We use cookies and other technical information to personalise your visit, analyse traffic, and track user selections.</p>
                  <p>Cookies can either be permanent or temporary. You can configure your browser to alert you when we attempt to send a cookie, with an option to accept or refuse it.</p>
                </>
              )
            },
            {
              id: 'security-links',
              title: '9. Security & Third-Party Links',
              icon: <Lock size={18} />,
              content: (
                <>
                  <p>The GHL India Asset V PVT LTD Website/App has stringent security measures in place to protect the loss, misuse, and alteration of details under our control. Whenever you access your account, we offer the use of a secure server.</p>
                  <p>During interactions, we may provide links to third-party websites. GHL India Asset V PVT LTD is not responsible for the availability, content, terms of use, privacy policies, and practices of such third-party websites.</p>
                </>
              )
            },
            {
              id: 'compliance-grievance',
              title: '10. Compliance & Grievance Redressal',
              icon: <Shield size={18} />,
              content: (
                <>
                  <p>This Privacy Policy is governed by the laws of India. You may update your Personal Information or opt-out of promotional communications by emailing us at <a href="mailto:support@ghlindia.com">support@ghlindia.com</a>.</p>
                  <p><strong>Disclaimer as to Loss:</strong> Although we ensure security of collected data, the open nature of the Internet means information may be accessed by unauthorized Hackers. GHL India Asset V PVT LTD assumes no liability for Hacker intrusions.</p>
                  <p>In case of any grievance in respect of the Privacy Policy, the Company may be contacted from Mon to Sat (10:00 to 17:00) at: Email: <a href="mailto:sales@ghlindia.com">sales@ghlindia.com</a>.</p>
                </>
              )
            }
          ]
        };

      case 'cookies':
        return {
          title: 'Cookie Policy',
          subtitle: 'This Cookies Policy explains how We use cookies to deliver a secure and smooth platform experience.',
          lastUpdated: 'January 01, 2023',
          sections: [
            {
              id: 'definitions',
              title: '1. Interpretation & Definitions',
              icon: <FileText size={18} />,
              content: (
                <>
                  <p><strong>Company:</strong> Company (referred to as either "the Company", "We", "Us" or "Our") refers to GHL India Asset V PVT LTD, having registered office at 2D, Queens Court, No.6, Montieth Road, Egmore, Chennai, Tamil Nadu-600 008.</p>
                  <p><strong>Cookies:</strong> Small files placed on your computer, mobile device, or other terminal by a website, containing details of your browsing history and session logs.</p>
                  <p><strong>You:</strong> Means the individual or legal entity accessing or using the Website as applicable.</p>
                </>
              )
            },
            {
              id: 'types',
              title: '2. Types of Cookies We Use',
              icon: <CheckCircle size={18} />,
              content: (
                <>
                  <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your device when you go offline, while Session Cookies are deleted when you close your web browser. We use both session and persistent Cookies:</p>
                  <ul>
                    <li><strong>Necessary / Essential Cookies (Session):</strong> Administered by Us, these cookies are essential to provide secure authentication, prevent account fraud, and maintain active investment sessions.</li>
                    <li><strong>Functionality Cookies (Persistent):</strong> Administered by Us, these cookies allow us to remember choices you make (such as language preferences or login credentials) to deliver a personalized experience.</li>
                  </ul>
                </>
              )
            },
            {
              id: 'choices',
              title: '3. Your Choices Regarding Cookies',
              icon: <Shield size={18} />,
              content: (
                <>
                  <p>If you prefer to avoid the use of Cookies on the Website, you must first disable the use of Cookies in your browser and then delete the Cookies saved in your browser history associated with this website.</p>
                  <p>Please note that if you do not accept our cookies, you may experience inconvenience in your use of the Website, and some secure features (such as logged-in portal forms) may not function properly.</p>
                </>
              )
            },
            {
              id: 'contacts',
              title: '4. Contact Details',
              icon: <Info size={18} />,
              content: (
                <>
                  <p>If you have any questions or feedback regarding this Cookies Policy, please reach out to us at:</p>
                  <ul>
                    <li>By email: <a href="mailto:sales@ghlindia.com">sales@ghlindia.com</a></li>
                    <li>By Address: GHL India Asset V PVT LTD, 2D, Queens Court, No.6, Montieth Road, Egmore, Chennai, Tamil Nadu - 600 008</li>
                  </ul>
                </>
              )
            }
          ]
        };

      default:
        return { title: '', subtitle: '', sections: [] };
    }
  };

  const data = getPolicyContent();

  return (
    <div className="policy-wrapper">
      {/* Page Header */}
      <section className="policy-header-section">
        <div className="container">
          <div className="policy-breadcrumbs">
            <span onClick={() => window.location.hash = '#/'} className="policy-crumb-link">Home</span>
            <span className="policy-crumb-separator">/</span>
            <span className="policy-crumb-current">{data.title}</span>
          </div>
          <h1>{data.title}</h1>
          <p>{data.subtitle}</p>
          <div className="policy-meta">
            Last Updated: <strong>{data.lastUpdated}</strong>
          </div>
        </div>
      </section>

      {/* Main Section */}
      <section className="policy-content-section">
        <div className="container policy-layout-grid">
          
          {/* Left Sticky Sidebar */}
          <aside className="policy-sidebar">
            <div className="policy-sticky-card">
              <h3>Table of Contents</h3>
              <nav className="policy-nav-links">
                {data.sections.map((sec) => (
                  <button
                    key={sec.id}
                    className={`policy-nav-btn ${activeSection === sec.id ? 'active' : ''}`}
                    onClick={() => handleScrollTo(sec.id)}
                  >
                    {sec.icon}
                    <span>{sec.title}</span>
                  </button>
                ))}
              </nav>
            </div>
          </aside>

          {/* Right Scrollable Content */}
          <article className="policy-text-body">
            {data.sections.map((sec) => (
              <div key={sec.id} id={sec.id} className="policy-section-block">
                <h2>{sec.title}</h2>
                <div className="section-divider"></div>
                <div className="policy-section-text">
                  {sec.content}
                </div>
              </div>
            ))}
          </article>

        </div>
      </section>
    </div>
  );
}
